# Generated by Django 5.1 on 2024-08-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_linsting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Linsting',
            new_name='Listing',
        ),
    ]
