# Generated by Django 5.1 on 2024-08-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(choices=[('RECORD', 'Record'), ('CLOTHING', 'Clothing'), ('POSTER', 'Poster'), ('DIVERS', 'Divers')], default=2000),
            preserve_default=False,
        ),
    ]
